apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-image-deployment
spec:
  selector:
    matchLabels:
      app: django-image
  replicas: 4
  template:
    metadata:
      labels:
        app:django-image
    spec:
      containers:
      - name: django-image
        image: ghtjd22103/django-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
